name = "MC 1.18 Modpack"
author = "SteelPh0enix"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c8de4b48e6cf32bec12419446222ccb283d567ff10c08f3d122729d601246be"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
