name = "MC 1.18 Modpack"
author = "SteelPh0enix"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0db68d1ecf7451e02a3086c8bdd498a8c86d19ec7de1342132cbd74e77b7ced0"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
