name = "MC 1.18 Modpack"
author = "SteelPh0enix"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe30d2a6ceb074e0d3eec90e1e5aa8f259ab0f38b6d03ac473a4bc9cadc0a4ea"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
