name = "MC 1.18 Modpack"
author = "SteelPh0enix"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1c58c206c4016a227e6578eaea7e78228c11c21fa2adb276bbee183625bf14c"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
