name = "MC 1.18 Modpack"
author = "SteelPh0enix"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d306e4e35b0ab4da1a9a981dfc19fb79c5ab0a6242b6525bfc2c9d8620a9bf24"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
