name = "MC 1.18 Modpack"
author = "SteelPh0enix"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "380cfe5e10f67bfcd195437050920d2e9bca26034359701e9dc1e02ebe663e49"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
