name = "Applied Energistics 2"
filename = "appliedenergistics2-10.1.0-beta.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/160/appliedenergistics2-10.1.0-beta.2.jar"
hash-format = "sha1"
hash = "fdc5f2557bc3f9d7461ce03321ee98cc5fa629b8"

[update]
[update.curseforge]
file-id = 3646160
project-id = 223794
