name = "BetterF3"
filename = "BetterF3-1.2.2-Fabric-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3551/264/BetterF3-1.2.2-Fabric-1.18.jar"
hash-format = "sha1"
hash = "e5140d6e028985031d99fd6493af279f22b65290"

[update]
[update.curseforge]
file-id = 3551264
project-id = 401648
