name = "Blockus"
filename = "blockus-2.3.6+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/94/blockus-2.3.6+1.18.1.jar"
hash-format = "sha1"
hash = "b901a6ddd0ea7d8842136d4cfc16d4751588efe2"

[update]
[update.curseforge]
file-id = 3670094
project-id = 312289
