name = "Bookshelf"
filename = "Bookshelf-Fabric-1.18.1-12.0.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/434/Bookshelf-Fabric-1.18.1-12.0.21.jar"
hash-format = "sha1"
hash = "f759dc9b1f94a84cb758110921be11ea429344d8"

[update]
[update.curseforge]
file-id = 3669434
project-id = 228525
