name = "Break Progress"
filename = "breakprogress-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3133/167/breakprogress-1.0.1.jar"
hash-format = "sha1"
hash = "cad6999109f1f156e2cd2be7eabb4c528d24b4a5"

[update]
[update.curseforge]
file-id = 3133167
project-id = 416406
