name = "CleanCut"
filename = "cleancut-1.18-4.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/604/cleancut-1.18-4.0-fabric.jar"
hash-format = "sha1"
hash = "5d17070b7d6be8c66a8f29527e18a0ef0448514e"

[update]
[update.curseforge]
file-id = 3549604
project-id = 392805
