name = "Clumps"
filename = "Clumps-fabric-1.18.1-8.0.0+5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3616/323/Clumps-fabric-1.18.1-8.0.0+5.jar"
hash-format = "sha1"
hash = "d0b0974f63a1f9618657e8ef16dba7909ef2a13e"

[update]
[update.curseforge]
file-id = 3616323
project-id = 256717
