name = "Comforts (Fabric)"
filename = "comforts-fabric-1.0.3-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/443/comforts-fabric-1.0.3-1.18.1.jar"
hash-format = "sha1"
hash = "a6314b3010e158d2ea6c8b806453b9100e9b7cdf"

[update]
[update.curseforge]
file-id = 3681443
project-id = 433539
