name = "Controlling"
filename = "Controlling-fabric-1.18.1-9.0+15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/601/Controlling-fabric-1.18.1-9.0+15.jar"
hash-format = "sha1"
hash = "138070f68e7e42a7828c36f263cfec9eb86c6731"

[update]
[update.curseforge]
file-id = 3648601
project-id = 250398
