name = "Diggus Maximus"
filename = "diggusmaximus-1.5.3-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/928/diggusmaximus-1.5.3-1.18.jar"
hash-format = "sha1"
hash = "2a162dd905750e7731306ac6715268b02d531c9f"

[update]
[update.curseforge]
file-id = 3667928
project-id = 341888
