name = "Dynamic View[Forge/Fabric]"
filename = "dynview.fabric-1.18-1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3675/463/dynview.fabric-1.18-1.7.jar"
hash-format = "sha1"
hash = "891550cc44e0e5896a69bc468249e73921581c80"

[update]
[update.curseforge]
file-id = 3675463
project-id = 366140
