name = "Extra Alchemy"
filename = "extraalchemy-fabric-1.18.1-1.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3595/791/extraalchemy-fabric-1.18.1-1.7.0.jar"
hash-format = "sha1"
hash = "64e9bfd77cbf76be2ef54e814f2763cd3bac698d"

[update]
[update.curseforge]
file-id = 3595791
project-id = 247357
