name = "Illuminations 🔥"
filename = "illuminations-1.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/673/illuminations-1.10.2.jar"
hash-format = "sha1"
hash = "013e14f861c7c996b5a0bf8dbdcbbe45da7f2de1"

[update]
[update.curseforge]
file-id = 3542673
project-id = 292908
