name = "Indium"
filename = "indium-1.0.2-alpha2+mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/937/indium-1.0.2-alpha2+mc1.18.1.jar"
hash-format = "sha1"
hash = "111912f57b1edd769b19c24419390db0652fd0c6"

[update]
[update.curseforge]
file-id = 3606937
project-id = 459496
