name = "Inventory HUD+"
filename = "InventoryHUD-fabric-1.18-3.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/928/InventoryHUD-fabric-%5B1.18%5D%20-3.4.2.jar"
hash-format = "sha1"
hash = "86b117c3c6978013468adbeb3f74e98328febda1"

[update]
[update.curseforge]
file-id = 3545928
project-id = 357540
