name = "Flytre Lib (FlytreLib)"
filename = "flytre_lib-1.18.1-1.7.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/413/flytre_lib-1.18.1-1.7.1-fabric.jar"
hash-format = "sha1"
hash = "9cbab488951bf34e48ba2aca91ec4f14dc1293d6"

[update]
[update.curseforge]
file-id = 3630413
project-id = 444498
