name = "Mouse Tweaks"
filename = "MouseTweaks-fabric-mc1.18-2.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/896/MouseTweaks-fabric-mc1.18-2.22.jar"
hash-format = "sha1"
hash = "204b054b2dd027014c8dd346e64c4cd2cc1db9b0"

[update]
[update.curseforge]
file-id = 3601896
project-id = 60089
