name = "Nature's Compass"
filename = "NaturesCompass-1.18.1-2.0.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3569/968/NaturesCompass-1.18.1-2.0.2-fabric.jar"
hash-format = "sha1"
hash = "b6abf95fcf57295e0a0f316293acd86e8eb0358f"

[update]
[update.curseforge]
file-id = 3569968
project-id = 252848
