name = "NinjaPhenix's Container Library"
filename = "ninjaphenix-container-library-1.3.0+1.18-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/305/ninjaphenix-container-library-1.3.0+1.18-fabric.jar"
hash-format = "sha1"
hash = "32670d31b6ae25dc1bf5683983362a3ad97223e5"

[update]
[update.curseforge]
file-id = 3649305
project-id = 530668
