name = "Paintings ++"
filename = "Paintings-fabric-1.18.1-9.1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/673/Paintings-fabric-1.18.1-9.1.0.0.jar"
hash-format = "sha1"
hash = "8f3e20ed138006ce73664b1deff73fb73c177b7d"

[update]
[update.curseforge]
file-id = 3604673
project-id = 252042
