name = "Sodium"
filename = "sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/309/sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar"
hash-format = "sha1"
hash = "795d4c12bffdb1b21eed5ff87c07ce5ca3c0dcbf"

[update]
[update.curseforge]
file-id = 3605309
project-id = 394468
