name = "WTHIT"
filename = "wthit-fabric-4.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3662/798/wthit-fabric-4.5.4.jar"
hash-format = "sha1"
hash = "8c74b5cc81b7de41b7773246a08fbc98b27ac867"

[update]
[update.curseforge]
file-id = 3662798
project-id = 440979
