name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.2.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3663/92/youre-in-grave-danger-1.2.20.jar"
hash-format = "sha1"
hash = "108d53f76cb159daebb6bc52c2f81c9540dddf89"

[update]
[update.curseforge]
file-id = 3663092
project-id = 544912
